language: objective-c
osx_image: xcode9
xcode_project: DreamBig.xcodeproj
xcode_scheme: DreamBig 

install:
  - ./Scripts/install_swiftlint.sh

script:
  - set -o pipefail && xcodebuild -project DreamBig.xcodeproj -scheme DreamBig -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch)' | xcpretty
